/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tonyu_kernel_TonyuOpenGL11Drawer_DrawPack */

#ifndef _Included_tonyu_kernel_TonyuOpenGL11Drawer_DrawPack
#define _Included_tonyu_kernel_TonyuOpenGL11Drawer_DrawPack
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
