/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tonyu_kernel_TonyuOpenGL11Drawer */

#ifndef _Included_tonyu_kernel_TonyuOpenGL11Drawer
#define _Included_tonyu_kernel_TonyuOpenGL11Drawer
#ifdef __cplusplus
extern "C" {
#endif
#undef tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWMETHOD
#define tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWMETHOD 0L
#undef tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWSPRITE
#define tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWSPRITE 16L
#undef tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWSPRITE_LT
#define tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWSPRITE_LT 17L
#undef tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWDXSPRITE
#define tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWDXSPRITE 32L
#undef tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWTEXT
#define tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWTEXT 48L
#undef tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWTEXTCC
#define tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWTEXTCC 49L
#undef tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWLINE
#define tonyu_kernel_TonyuOpenGL11Drawer_DPK_DRAWLINE 64L
#undef tonyu_kernel_TonyuOpenGL11Drawer_DPK_FILLRECT
#define tonyu_kernel_TonyuOpenGL11Drawer_DPK_FILLRECT 80L
/*
 * Class:     tonyu_kernel_TonyuOpenGL11Drawer
 * Method:    allDraw_NDK
 * Signature: (Ljava/lang/Object;Z)V
 */
JNIEXPORT void JNICALL Java_tonyu_kernel_TonyuOpenGL11Drawer_allDraw_1NDK
  (JNIEnv *, jobject, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
